"""set file id int to uuid2

Revision ID: 81698f2b8e8c
Revises: 67ad89bc0e87
Create Date: 2025-10-06 13:48:35.263436

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '81698f2b8e8c'
down_revision: Union[str, Sequence[str], None] = '67ad89bc0e87'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # 启用 pgcrypto 扩展以使用 gen_random_uuid()
    op.execute('CREATE EXTENSION IF NOT EXISTS "pgcrypto";')

    # Step 1: 给 files 表添加新 UUID 列
    op.execute('ALTER TABLE files ADD COLUMN new_id uuid DEFAULT gen_random_uuid();')

    # Step 2: 给 document_chunks 表添加新外键列
    op.execute('ALTER TABLE document_chunks ADD COLUMN new_document_id uuid;')

    # Step 3: 将旧的 int id 映射到新的 uuid（这里生成随机 UUID，原 ID 不保留）
    op.execute('UPDATE document_chunks SET new_document_id = gen_random_uuid();')
    op.execute('UPDATE files SET new_id = gen_random_uuid();')

    # ⚠️ 如果你想保持外键关系一致（旧id → 新id），可以改成这种方式：
    #    先导出映射表或用 join 更新，这部分我可以帮你写完整SQL。

    # Step 4: 删除外键约束
    op.drop_constraint('document_chunks_document_id_fkey', 'document_chunks', type_='foreignkey')

    # Step 5: 删除旧主键、旧列
    op.execute('ALTER TABLE files DROP CONSTRAINT files_pkey;')
    op.execute('ALTER TABLE files DROP COLUMN id;')

    # Step 6: 重命名新列
    op.execute('ALTER TABLE files RENAME COLUMN new_id TO id;')

    # Step 7: 重建主键
    op.execute('ALTER TABLE files ADD PRIMARY KEY (id);')

    # Step 8: 删除旧外键列并重命名新列
    op.execute('ALTER TABLE document_chunks DROP COLUMN document_id;')
    op.execute('ALTER TABLE document_chunks RENAME COLUMN new_document_id TO document_id;')

    # Step 9: 新外键约束
    op.create_foreign_key(
        'document_chunks_document_id_fkey',
        source_table='document_chunks',
        referent_table='files',
        local_cols=['document_id'],
        remote_cols=['id'],
        ondelete='CASCADE'
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_files_id'), 'files', ['id'], unique=False)
    op.alter_column('files', 'id',
               existing_type=sa.Uuid(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('document_chunks', 'document_id',
               existing_type=sa.Uuid(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    # ### end Alembic commands ###
