"""add config id3

Revision ID: abf6ab1b16d2
Revises: a63a144569a0
Create Date: 2025-10-06 18:38:37.537478

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'abf6ab1b16d2'
down_revision: Union[str, Sequence[str], None] = 'a63a144569a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('titles', sa.Column('load_config_id', sa.Uuid(), nullable=True))
    op.drop_index(op.f('ix_titles_llm_config_id'), table_name='titles')
    op.create_index(op.f('ix_titles_load_config_id'), 'titles', ['load_config_id'], unique=False)
    op.drop_constraint(op.f('titles_llm_config_id_fkey'), 'titles', type_='foreignkey')
    op.create_foreign_key(None, 'titles', 'load_configs', ['load_config_id'], ['id'])
    op.drop_column('titles', 'llm_config_id')
    op.add_column('users', sa.Column('cur_llm_config_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_users_cur_llm_config_id'), 'users', ['cur_llm_config_id'], unique=False)
    op.create_foreign_key(None, 'users', 'query_configs', ['cur_llm_config_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_index(op.f('ix_users_cur_llm_config_id'), table_name='users')
    op.drop_column('users', 'cur_llm_config_id')
    op.add_column('titles', sa.Column('llm_config_id', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'titles', type_='foreignkey')
    op.create_foreign_key(op.f('titles_llm_config_id_fkey'), 'titles', 'query_configs', ['llm_config_id'], ['id'])
    op.drop_index(op.f('ix_titles_load_config_id'), table_name='titles')
    op.create_index(op.f('ix_titles_llm_config_id'), 'titles', ['llm_config_id'], unique=False)
    op.drop_column('titles', 'load_config_id')
    # ### end Alembic commands ###
